### ISSUE TITLE
Mosquitto connection problem

### ISSUE THREAD

**Issue by Legobas** [sourcesimian/mqtt-panel#5]
In my situation mqtt-panel cannot connect to Mosquitto.
The connection is secured with username/password.

First I tried the Docker image, after login an error message is shown.
This is the log:

> today at 21:35:082022-01-14 21:35:08,923 INFO [mqtt] Open (mqtt-panel)
today at 21:35:082022-01-14 21:35:08,925 INFO [mqtt] Using basic auth
today at 21:35:082022-01-14 21:35:08,926 INFO [mqtt] Connecting to 192.168.1.250:1883
today at 21:35:082022-01-14 21:35:08,934 INFO [mqtt] Open (mqtt-panel)
today at 21:35:082022-01-14 21:35:08,937 INFO [mqtt] Using basic auth
today at 21:35:082022-01-14 21:35:08,938 INFO [mqtt] Connecting to 192.168.1.250:1883
today at 21:35:082022-01-14 21:35:08,945 INFO [mqtt] On Connect
today at 21:35:082022-01-14 21:35:08,949 INFO [mqtt] On Disconnect
today at 21:35:082022-01-14 21:35:08,950 INFO [mqtt] Close
today at 21:35:082022-01-14 21:35:08,951 INFO [mqtt] Open (mqtt-panel)
today at 21:35:082022-01-14 21:35:08,953 INFO [mqtt] Using basic auth
today at 21:35:082022-01-14 21:35:08,954 INFO [mqtt] Connecting to 192.168.1.250:1883

My next step was to run the Python program on my own computer.
But I am not a Python developer so it is difficult for me to trace down the problem.

It seems to be a problem with the paho.mqtt.client.
I tried several options with the paho.mqtt.client.Client like this:

>         self._client = paho.mqtt.client.Client(client_id=self._c['client-id'], userdata=None, protocol=paho.mqtt.client.MQTTv5, transport="tcp")

        self._client = paho.mqtt.client.Client(client_id=self._c['client-id'], userdata=None, protocol=paho.mqtt.client.MQTTv311, transport="tcp")

but that did not solve the problem.

This is the message in the Mosquitto log:

> Socket error on client <unknown>, disconnecting.

It seems to be a known problem with the Python Paho MQTT Client but I am not sure about that.
Is it possible to show debug log messages for the Paho MQTT Client?
Do you have other suggestions?

**Comment by sourcesimian** [comment]
Thank you for your feedback. I'll take a look and see what I can find.

**Comment by sourcesimian** [comment]
There was a bug in the MQTT basic auth. Thank you for taking the time to highlight this issue. Should be resolved in v0.0.4

**Comment by Legobas** [comment]
It works perfectly now, thank you very much!
